### PR TITLE
Updated JetBrains.Rider.SDK package versions to the latest release.

### LINKED ISSUE #202: Consider changing the until-build idea-version property in plugin.xml to automatically support new Rider versions
Whenever a new version of rider is shipped (either EAP or regular) the idea-version will change. Currently in https://github.com/SpecFlowOSS/SpecFlow.Rider/blob/281f68fc4a1079808181610ea54f7a6bb5595097/src/rider/main/resources/META-INF/plugin.xml#L6 the plugins until-build version is set to _\_PLACEHOLDER\__. Which is replaced with for instance '232.*', meaning **only** 2023.2 releases are supported. 
This has the effect that the plugin cannot be installed into 2023.3 instances regardless of whether the plugin would work.

The Rider marketplace has a mechanism to check whether a plugin is able to work with new rider versions by checking the used dlls/apis for breaking changes. Whenever a breaking change is found it will not allow users to install the plugin into that version. The owner will then get an email with compatibility results. 

Setting the until-build version to _**\***_ instead of _\_PLACEHOLDER\__ will allow this mechanism to work correctly and result in less releases needed to support newer Rider versions and for users to hopefully have to spend less time on older Rider versions, just because this plugin cannot be installed into the newer versions.

Information about this mechanism has been kindly supplied by @citizenmatt :)

### PR DESCRIPTION
**Pull request by ajeckmans**
Set until-build in plugin metadata to * to allow marketplace mechanism to determine if the plugin will work with newer Rider versions or not.
Fixes #202

### CODE REVIEW

**Comment by ajeckmans** [comment]
I had to update the version of NUnit3TestAdapter because it failed on some weird error about not knowing SDK 7 (even though I have that installed). The newer version fixed that.

**Comment by Socolin** [comment]
Hello, the version need to be updated in [gradle.properties](https://github.com/SpecFlowOSS/SpecFlow.Rider/blob/master/gradle.properties) too.

**Comment by ajeckmans** [comment]
@Socolin The build is working locally as well as the gradlew thing. There are some warnings, but nothing major. I'm not sure why it is failing in the build itself?

**Comment by Socolin** [comment]
Since it fail during the protocol steps maybe the package need to be updated too (top of build.gradle 'com.jetbrains.rdgen')

**Comment by ajeckmans** [comment]
This is my first time "working" on a plugin for rider/resharper, but wow.. this is getting way more complicated than expected :)

**Comment by Socolin** [comment]
You should not replace the variable here

```
-    <PackageReference Include="JetBrains.Rider.SDK" Version="$(SdkVersion)" />
+    <PackageReference Include="JetBrains.Rider.SDK" Version="2023.2.3" />
```

This need to be updated in the `.props` file

**Comment by Socolin** [comment]
> This is my first time "working" on a plugin for rider/resharper, but wow.. this is getting way more complicated than expected :)

For every release I have to take 1 evening to updates all my plugin and find the right combinaison of version for gradle, jvm, nugets, etc... 

One way to find out the version to use is to check https://github.com/JetBrains/resharper-rider-plugin

**Comment by ajeckmans** [comment]
I will look at that this evening then.

Also I changed the version in the wrong file initially. Then corrected it and did the unspeakable: an amend and force push, so your local history might be different now. Sorry for that :)

**Comment by Socolin** [comment]
No problem with force push :)

**Comment by ajeckmans** [comment]
@Socolin and now? 😄

**Comment by Socolin** [comment]
Look good thanks ! :)

I'll submit a new version and in 1 or 2 days it should be available, if you want to install on your side you can install from zip (there is a button for that in the Plugin UI)

**Pull request merged**
