### PR TITLE
Build against 2023.3-EAP7-SNAPSHOT

### PR DESCRIPTION
**Pull request by ajeckmans**
Build against 2023.3-EAP7-SNAPSHOT and properly set the target version to the 2023.* range of versions (any less restrictive does not work).

### CODE REVIEW

**Comment by Socolin** [comment]
Look good, can you just add the Changelog too ?

**Comment by ajeckmans** [comment]
@Socolin there was still an issue. Let me fix that first

**Comment by ajeckmans** [comment]
There :)

**Comment by Socolin** [comment]
Were you able to run the build ? I'm getting errors when testing it.

To test you should be able to run `./gradlew :runIde`  (or the `.bat`  on windows)

You miss the update in `Plugin.props`, I'll fix this

**Comment by ajeckmans** [comment]
I was running it using the rider launch thingie and there it was loading the plugin.
I'll run that command next time :)

**Pull request merged**
